server:
  port: 8078

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bcf23-prometheus/data-configs
          username: ${CLOUD_CONFIG_GITHUB_TOKEN}
          password: ${CLOUD_CONFIG_GITHUB_TOKEN}
          default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8079/eureka/
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
